package expect

import (
	"errors"
	"fmt"
	"runtime"
	"strings"
	"unicode"
	"unicode/utf8"
)

type (
	// TB is a cut-down version of testing.TB.
	TB interface {
		Error(args ...any)
		Errorf(format string, args ...any)
		Fatalf(format string, args ...any)
		Helper()
	}
	Inspector[T any] struct {
		t       TB
		Subject T
	}
)

// It is the entry point for the matcher DSL. Pass in the testing.TB and the subject you want to test.
func It[T any](t TB, subject T) Inspector[T] {
	return Inspector[T]{t, subject}
}

// To is the method that actually runs the matchers. It will call Errorf on the testing.TB if any of the matchers fail.
func (e Inspector[T]) To(matchers ...Matcher[T]) {
	e.t.Helper()
	stackTrace := callerInfo()
	for _, matcher := range matchers {
		result := matcher(e.Subject)
		
		if result.SubjectName == "" {
			result.SubjectName = calculateSubjectName(e)
		}
		
		if !result.Matches {
			result.StackTrace = stackTrace
			e.t.Error(result.Error())
		}
	}
}

// NoError is a helper function that will call t.Fatalf if the error is not nil.
func NoError(t TB, err error) {
	t.Helper()
	if err == nil {
		return
	}
	format, args := "unexpected error: %v", []any{err}
	if fieldFormat, fieldArg, ok := getErrFieldsStr(err); ok {
		format += "\n" + fieldFormat
		args = append(args, fieldArg)
	}
	args = append(args, stackTraceField(callerInfo()))
	t.Fatalf(format+"%s", args...)
}

func getErrFieldsStr(err error) (string, string, bool) {
	fielder, ok := err.(interface{ Fields() []any })
	if !ok && fielder == nil || len(fielder.Fields()) == 0 {
		return "", "", false
	}

	fields := fielder.Fields()

	var sb strings.Builder
	for i := 0; i < len(fields); i += 2 {
		k := fields[i]
		var v any
		if vIdx := i + 1; vIdx < len(fields) {
			v = fields[vIdx]
		}
		if s, _ := k.(string); s == "stack_trace" {
			fmt.Fprintf(&sb, "\n\t%s=[", s)
			vs, ok := v.([]string)
			if ok {
				for _, vf := range vs {
					sb.WriteString("\n\t\t")
					fmt.Fprintf(&sb, "%s,", vf)
				}
			}
			if len(vs) > 0 {
				sb.WriteString("\n\t")
			}
			sb.WriteRune(']')
			continue
		}
		fmt.Fprintf(&sb, "\n\t%v=%v", k, v)
	}

	return "fields: %s", sb.String(), true
}

// Error is a helper function that will call t.Fatalf if the error is nil.
func Error(t TB, err error) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected an error%s", stackTraceField(callerInfo()))
	}
}

// ErrorOfType is a helper function that will call t.Fatalf if the error is not of the expected type.
func ErrorOfType(t TB, err error, expectedType error) {
	t.Helper()
	if !errors.Is(err, expectedType) {
		t.Fatalf("expected error of type %T, but got %q%s", expectedType, err.Error(), stackTraceField(callerInfo()))
	}
}

func calculateSubjectName[T any](e Inspector[T]) string {
	var subjectName = fmt.Sprintf("%+v", e.Subject)

	if str, isStringer := any(e.Subject).(fmt.Stringer); isStringer {
		subjectName = str.String()
	}
	return subjectName
}

const stackFrameBufferSize = 10

func callerInfo() []string {
	var pc uintptr
	var file string
	var line int
	var name string

	pcs := make([]uintptr, stackFrameBufferSize)

	callers := []string{}
	offset := 1

	for {
		n := runtime.Callers(offset, pcs)

		if n == 0 {
			break
		}

		frames := runtime.CallersFrames(pcs[:n])

		for {
			frame, more := frames.Next()
			pc = frame.PC
			file = frame.File
			line = frame.Line

			if file == "<autogenerated>" {
				break
			}

			f := runtime.FuncForPC(pc)
			if f == nil {
				break
			}
			name = f.Name()

			if name == "testing.tRunner" {
				break
			}

			parts := strings.Split(file, "/")
			if len(parts) > 1 {
				filename := parts[len(parts)-1]
				dir := parts[len(parts)-2]
				if dir != "expect" || filename == "_test.go" {
					callers = append(callers, fmt.Sprintf("%s:%d", file, line))
				}
			}

			dotPos := strings.LastIndexByte(name, '.')
			name = name[dotPos+1:]
			if isTest(name, "Test") ||
				isTest(name, "Benchmark") ||
				isTest(name, "Example") {
				break
			}

			if !more {
				break
			}
		}

		offset += cap(pcs)
	}

	return callers
}

func isTest(name, prefix string) bool {
	if !strings.HasPrefix(name, prefix) {
		return false
	}
	if len(name) == len(prefix) {
		return true
	}
	r, _ := utf8.DecodeRuneInString(name[len(prefix):])
	return !unicode.IsLower(r)
}

func stackTraceField(stackTrace []string) string {
	if len(stackTrace) == 0 {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("\nError Trace:\n")
	for _, trace := range stackTrace {
		sb.WriteString("\t")
		sb.WriteString(trace)
		sb.WriteString("\n")
	}
	return sb.String()
}
